package com.example.quemessepokemon.Classes;

import android.app.Application;
import android.graphics.Bitmap;
import android.graphics.BitmapFactory;
import android.media.Image;
import android.net.Uri;
import android.widget.ImageView;
import android.widget.Toast;

import com.example.quemessepokemon.Activities.Quem_Eh_Esse_Pokemon;

import java.io.File;
import java.io.InputStream;
import java.util.Random;

public class Pokemon extends Application {
    private static String[] pokemons = {
            "bulbasaur",
            "ivysaur",
            "venusaur",
            "mega venusaur",
            "charmander",
            "charmeleon",
            "charizard",
            "mega charizard x",
            "mega charizard y",
            "squirtle",
            "wartortle",
            "blastoise",
            "mega blastoise",
            "caterpie",
            "metapod",
            "butterfree",
            "weedle",
            "kakuna",
            "beedrill",
            "mega beedrill",
            "pidgey",
            "pidgeotto",
            "pidgeot",
            "mega pidgeot",
            "rattata",
            "raticate",
            "spearow",
            "fearow",
            "ekans",
            "arbok",
            "pikachu",
            "raichu",
            "sandshrew",
            "sandslash",
            "nidoran",
            "nidorina",
            "nidoqueen",
            "nidoranM",
            "nidorino",
            "nidoking",
            "clefairy",
            "clefable",
            "vulpix",
            "ninetales",
            "jigglypuff",
            "wigglypuff",
            "zubat",
            "golbat",
            "oddish",
            "gloom",
            "vileplume",
            "paras",
            "parasect",
            "venonat",
            "venomoth",
            "diglett",
            "dugtrio",
            "meowth",
            "persian",
            "psyduck",
            "golduck",
            "mankey",
            "primeape",
            "growlithe",
            "arcanine",
            "poliwag",
            "poliwhirl",
            "poliwrath",
            "abra",
            "kadabra",
            "alakazam",
            "mega alakazam",
            "machop",
            "machoke",
            "machamp",
            "bellsprout",
            "weepinbell",
            "victreebell",
            "tentacool",
            "tentacruel",
            "geodude",
            "graveler",
            "golem",
            "ponyta",
            "rapidash",
            "slowpoke",
            "slowbro",
            "mega slowbro",
            "magnemite",
            "magneton",
            "farfetch'd",
            "doduo",
            "dodrio",
            "seel",
            "dewgong",
            "grimer",
            "muk",
            "shellder",
            "cloyster",
            "gastly",
            "haunter",
            "gengar",
            "mega gengar",
            "onix",
            "drowzee",
            "hypno",
            "krabby",
            "kingler",
            "voltorb",
            "electrode",
            "exeggcute",
            "exeggutor",
            "cubone",
            "marowak",
            "hitmonlee",
            "hitmonchan",
            "lickitung",
            "koffing",
            "weezing",
            "rhyhorn",
            "rhydon",
            "chansey",
            "tangela",
            "kangaskhan",
            "mega kangaskhan",
            "horsea",
            "seadra",
            "goldeen",
            "seaking",
            "staryu",
            "starmie",
            "mr. mime",
            "scyther",
            "jynx",
            "electabuzz",
            "magmar",
            "pinsir",
            "mega pinsir",
            "tauros",
            "magikarp",
            "gyarados",
            "mega gyarados",
            "lapras",
            "ditto",
            "eevee",
            "vaporeon",
            "jolteon",
            "flareon",
            "porygon",
            "omanyte",
            "omastar",
            "kabuto",
            "kabutops",
            "aerodactyl",
            "mega aerodactyl",
            "snorlax",
            "articuno",
            "zapdos",
            "moltres",
            "dratini",
            "dragonair",
            "dragonite",
            "mewtwo",
            "mega mewtwo x",
            "mega mewtwo y",
            "mew",
            "chikorita",
            "bayleef",
            "meganium",
            "cyndaquil",
            "quilava",
            "typhlosion",
            "totodile",
            "croconaw",
            "feraligatr",
            "sentret",
            "furret",
            "hoothoot",
            "noctowl",
            "ledyba",
            "ledian",
            "spinarak",
            "ariados",
            "crobat",
            "chinchou",
            "lanturn",
            "pichu",
            "cleffa",
            "igglybuff",
            "togepi",
            "togetic",
            "natu",
            "xatu",
            "mareep",
            "flaaffy",
            "ampharos",
            "mega ampharos",
            "bellossom",
            "marill",
            "azumarill",
            "sudowoodo",
            "politoed",
            "hoppip",
            "skiploom",
            "jumpluff",
            "aipom",
            "sunkern",
            "sunflora",
            "yanma",
            "wooper",
            "quagsire",
            "espeon",
            "umbreon",
            "murkrow",
            "slowking",
            "misdreavus",
            "unown",
            "wobbuffet",
            "girafarig",
            "pineco",
            "forretress",
            "dunsparce",
            "gligar",
            "steelix",
            "mega steelix",
            "snubbull",
            "granbull",
            "qwillfish",
            "scizor",
            "mega scizor",
            "shuckle",
            "heracross",
            "mega heracross",
            "sneasel",
            "teddiursa",
            "ursaring",
            "slugma",
            "magcargo",
            "swinub",
            "piloswine",
            "corsola",
            "remoraid",
            "octillery",
            "delibird",
            "mantine",
            "skarmory",
            "houndour",
            "houndoom",
            "mega houndoom",
            "kingdra",
            "phanpy",
            "donphan",
            "porygon2",
            "stantler",
            "smeargle",
            "tyrogue",
            "hitmontop",
            "smoochum",
            "elekid",
            "magby",
            "miltank",
            "blissey",
            "raikou",
            "entei",
            "suicune",
            "larvitar",
            "pupitar",
            "tyranitar",
            "mega tyranitar",
            "lugia",
            "ho-oh",
            "celebi",
            "treecko",
            "grovyle",
            "sceptile",
            "mega sceptile",
            "torchic",
            "combusken",
            "blaziken",
            "mega blaziken",
            "mudkip",
            "marshtomp",
            "swampert",
            "mega swampert",
            "poochyena",
            "mightyena",
            "zigzagoon",
            "linoone",
            "wurmple",
            "silcoon",
            "beautifly",
            "cascoon",
            "dustox",
            "lotad",
            "lombre",
            "ludicolo",
            "seedot",
            "nuzleaf",
            "shiftry",
            "taillow",
            "swellow",
            "wingull",
            "pelipper",
            "ralts",
            "kirlia",
            "gardevoir",
            "mega gardevoir",
            "surskit",
            "masquerain",
            "shroomish",
            "breloom",
            "slakoth",
            "vigoroth",
            "slaking",
            "nincada",
            "ninjask",
            "shedinja",
            "whismur",
            "loudred",
            "exploud",
            "makuhita",
            "hariyama",
            "azurill",
            "nosepass",
            "skitty",
            "delcatty",
            "sableye",
            "mega sableye",
            "mawile",
            "mega mawile",
            "aron",
            "lairon",
            "aggron",
            "mega aggron",
            "meditite",
            "medicham",
            "mega medicham",
            "electrike",
            "manectric",
            "mega manetric",
            "plusle",
            "minun",
            "volbeat",
            "illumise",
            "roselia",
            "gulpin",
            "swalot",
            "carvanha",
            "sharpedo",
            "mega sharpedo",
            "wailmer",
            "wailord",
            "numel",
            "camerupt",
            "mega camerupt",
            "torkoal",
            "spoink",
            "grumping",
            "spinda",
            "trapinch",
            "vibrava",
            "flygon",
            "cacnea",
            "cacturne",
            "swablu",
            "altaria",
            "mega altaria",
            "zangoose",
            "seviper",
            "lunatone",
            "solrock",
            "barboach",
            "whiscash",
            "corpish",
            "crawdaunt",
            "baltoy",
            "claydol",
            "lileep",
            "cradily",
            "anorith",
            "armaldo",
            "feebas",
            "milotic",
            "castform",
            "kecleon",
            "shuppet",
            "banette",
            "mega banette",
            "duskull",
            "dusclops",
            "tropius",
            "chimecho",
            "absol",
            "mega absol",
            "wynaut",
            "snorunt",
            "glalie",
            "mega glalie",
            "spheal",
            "sealeo",
            "walrein",
            "clamperl",
            "huntail",
            "gorebyss",
            "relicanth",
            "luvdisc",
            "bagon",
            "shelgon",
            "salamance",
            "mega salamance",
            "beldum",
            "metang",
            "metagross",
            "mega metagross",
            "regirock",
            "regice",
            "registeel",
            "latias",
            "mega latias",
            "latios",
            "mega latios",
            "kyogre",
            "groudon",
            "rayquaza",
            "mega rayquaza",
            "jirachi",
            "deoxys",
            "turtwig",
            "grotle",
            "torterra",
            "chimchar",
            "monferno",
            "infernape",
            "piplup",
            "prinplup",
            "empoleon",
            "starly",
            "staravia",
            "staraptor",
            "bidoof",
            "bibarel",
            "kricketot",
            "kricketune",
            "shinx",
            "luxio",
            "luxray",
            "budew",
            "roserade",
            "cranidos",
            "rampardos",
            "shieldon",
            "bastiodon",
            "burmy",
            "wormadam",
            "mothim",
            "combee",
            "vespiqueen",
            "pachirisu",
            "buizel",
            "floatzel",
            "cherubi",
            "cherrim",
            "shellos",
            "gastrodon",
            "ambipom",
            "drifloon",
            "drifblim",
            "buneary",
            "lopunny",
            "mega lopunny",
            "mismagius",
            "honchkrow",
            "glameow",
            "purugly",
            "chingling",
            "stunky",
            "skuntank",
            "bronzor",
            "bronzong",
            "bonsly",
            "mime jr.",
            "happiny",
            "chatot",
            "spiritbomb",
            "gible",
            "gabite",
            "garchomp",
            "mega garchomp",
            "munchlax",
            "riolu",
            "lucario",
            "mega lucario",
            "hippopotas",
            "hippowdon",
            "skorupi",
            "drapion",
            "croagunk",
            "toxicroak",
            "carnivine",
            "finneon",
            "lumineon",
            "mantyke",
            "snover",
            "abomasnow",
            "mega abomasnow",
            "weavile",
            "magnezone",
            "licklicky",
            "rhyperior",
            "tangrowth",
            "electivire",
            "magmortar",
            "togekiss",
            "yanmega",
            "leafeon",
            "glaceon",
            "gliscor",
            "mamoswine",
            "porygon-z",
            "gallade",
            "mega gallade",
            "probopass",
            "dusknoir",
            "froslass",
            "rotom",
            "uxie",
            "mesprit",
            "azelf",
            "dialga",
            "palkia",
            "heatran",
            "regigigas",
            "giratina",
            "cresselia",
            "phione",
            "manaphy",
            "darkrai",
            "shaymin",
            "arceus",
            "victini",
            "snivy",
            "servine",
            "serperior",
            "tepig",
            "pignite",
            "emboar",
            "oshawott",
            "dewott",
            "samurott",
            "patrat",
            "watchog",
            "lillipup",
            "herdier",
            "stoutland",
            "purrloin",
            "liepard",
            "pansage",
            "simsiage",
            "pansear",
            "simisear",
            "panpour",
            "simipour",
            "munna",
            "musharna",
            "pidove",
            "tranquill",
            "unfezant",
            "blitzle",
            "zebstrika",
            "roggenrola",
            "boldore",
            "gigalith",
            "woobat",
            "swoobat",
            "drilbur",
            "excadrill",
            "audino",
            "mega audino",
            "timburr",
            "gurdurr",
            "conkeldurr",
            "tympole",
            "palpitoad",
            "seismitoad",
            "throh",
            "sawk",
            "sewaddle",
            "swadloon",
            "leavanny",
            "venipede",
            "whirlipede",
            "scolipede",
            "cottonee",
            "whimsicott",
            "petilil",
            "lilligant",
            "basculin",
            "sandile",
            "krokorok",
            "krookodile",
            "darumaka",
            "damanitan",
            "maractus",
            "dwebble",
            "crustle",
            "scraggy",
            "scrafty",
            "sigilyph",
            "yamask",
            "cofagrigus",
            "tirtouga",
            "carracosta",
            "archen",
            "archeops",
            "trubbish",
            "garbodor",
            "zorua",
            "zoroark",
            "minccino",
            "cinccino",
            "gothita",
            "gothorita",
            "gothitelle",
            "solosis",
            "duosion",
            "reuniclus",
            "ducklett",
            "swanna",
            "vanillite",
            "vanillish",
            "vanilluxe",
            "deerling",
            "sawsbuck",
            "emolga",
            "karrablast",
            "escavalier",
            "foongus",
            "amoonguss",
            "frillish",
            "jellicent",
            "alomomola",
            "joltik",
            "galvantula",
            "ferroseed",
            "ferrothorn",
            "klink",
            "klang",
            "klinklang",
            "tynamo",
            "eelektrik",
            "eelektross",
            "elgyem",
            "beheeyem",
            "litwick",
            "lampent",
            "chandelure",
            "axew",
            "fraxure",
            "haxorus",
            "cubchoo",
            "beartic",
            "cryogonal",
            "shelmet",
            "accelgor",
            "stunfisk",
            "mienfoo",
            "mienshao",
            "druddigon",
            "golett",
            "golurk",
            "pawniard",
            "bisharp",
            "bouffalant",
            "rufflet",
            "braviary",
            "vullaby",
            "mandibuzz",
            "heatmor",
            "durant",
            "deino",
            "zweilous",
            "hydreigon",
            "larvesta",
            "volcarona",
            "cobalion",
            "terrakion",
            "virizion",
            "tornadus",
            "thundurus",
            "reshiram",
            "zekrom",
            "landorus",
            "kyurem",
            "keldeo",
            "meloetta",
            "genesect",
            "chespin",
            "quilladin",
            "chesnaught",
            "fennekin",
            "braixen",
            "delphox",
            "froakie",
            "frogadier",
            "greninja",
            "bunnelby",
            "diggersby",
            "fletchling",
            "fletchinder",
            "talonflame",
            "scatterbug",
            "spewpa",
            "vivillon",
            "litleo",
            "pyroar",
            "flabébé",
            "floette",
            "florges",
            "skiddo",
            "gogoat",
            "pancham",
            "pangoro",
            "furfrou",
            "espurr",
            "meowstic",
            "honedge",
            "doublade",
            "aegislash",
            "spritzee",
            "aromatisse",
            "swirlix",
            "slurpuff",
            "inkay",
            "malamar",
            "binacle",
            "barbaracle",
            "skrelp",
            "dragalge",
            "clauncher",
            "clawitzer",
            "helioptile",
            "heliolisk",
            "tyrunt",
            "tyrantrum",
            "amaura",
            "aurorus",
            "sylveon",
            "hawlucha",
            "dedenne",
            "carbink",
            "goomy",
            "sliggoo",
            "goodra",
            "klefki",
            "phantump",
            "trevenant",
            "pumpkaboo",
            "gourgeist",
            "bergmite",
            "avalugg",
            "noibat",
            "noivern",
            "xerneas",
            "yveltal",
            "zygarde",
            "diancie",
            "mega diancie",
            "hoopa",
            "volcanion",
            "rowlet",
            "dartrix",
            "decidueye",
            "litten",
            "torracat",
            "incineroar",
            "popplio",
            "brionne",
            "primarina",
            "pikipek",
            "trumbeak",
            "toucannon",
            "yungoos",
            "gumshoos",
            "grubbin",
            "charjabug",
            "vikavolt",
            "crabrawler",
            "crabominable",
            "oricorio",
            "cutiefly",
            "rimbobee",
            "rockruff",
            "lycanroc",
            "wishiwashi",
            "mareanie",
            "toxapex",
            "mudbray",
            "mudsdale",
            "dewpider",
            "araquanid",
            "fomantis",
            "lurantis",
            "morelull",
            "shiinotic",
            "salandit",
            "salazzle",
            "stufful",
            "bewear",
            "bounsweet",
            "steenee",
            "tsareena",
            "comfey",
            "oranguru",
            "passimian",
            "wimpod",
            "golisopod",
            "sandygast",
            "palossand",
            "pyukumuku",
            "type: null",
            "silvally",
            "minior",
            "komala",
            "turtonator",
            "togedemaru",
            "mimikyu",
            "bruxish",
            "drampa",
            "dhelmise",
            "jangmo-o",
            "hakamo-o",
            "kommo-o",
            "tapu koko",
            "tapu lele",
            "tapu bulu",
            "tapu fini",
            "cosmog",
            "cosmoem",
            "solgaleo",
            "lunala",
            "nihilego",
            "buzzwole",
            "phemorosa",
            "xurkitree",
            "celesteela",
            "kartana",
            "guzzlord",
            "necrozma",
            "magearna",
            "marshadow",
            "poipole",
            "nanagadel",
            "stakataka",
            "blacephalon",
            "zeraora",
            "meltan",
            "melmetal",
            "grookey",
            "thwackey",
            "rillaboom",
            "scorbunny",
            "raboot",
            "cinderace",
            "sobble",
            "drizzile",
            "inteleon",
            "skywovet",
            "greendent",
            "rookidee",
            "corvisquire",
            "corviknight",
            "blipbug",
            "dottler",
            "orbeetle",
            "nickit",
            "thievul",
            "grossifleur",
            "eldegoss",
            "wooloo",
            "dubwool",
            "chewtle",
            "drednaw",
            "yamper",
            "boltund",
            "rolycoly",
            "carkol",
            "coalossal",
            "applin",
            "flapple",
            "appletun",
            "silicobra",
            "sandaconda",
            "cramorant",
            "arrokuda",
            "barraskewda",
            "toxel",
            "toxtricity",
            "sizzlipede",
            "centiskorch",
            "clobbopus",
            "grapploct",
            "sinistea",
            "polteageist",
            "hatenna",
            "hattrem",
            "hatterene",
            "impidimp",
            "morgrem",
            "grimmsnarl",
            "obstagoon",
            "perrserker",
            "cursola",
            "sirfetch'd",
            "mr. rime",
            "runegirus",
            "milcery",
            "alcremie",
            "falinks",
            "pincurchin",
            "snom",
            "frosmoth",
            "stonjourner",
            "eiscue",
            "indeedee",
            "morpeko",
            "cufant",
            "copperajah",
            "dracozolt",
            "arctozolt",
            "dracovish",
            "arctovish",
            "duraludon",
            "dreepy",
            "drakloak",
            "dragapult",
            "zacian",
            "zamazenta",
            "eternatus",

    };
    private String nome;
    private String numero;

    public Pokemon(){

    }

    public Pokemon(String nome){
        if(contem(nome.toLowerCase())){
            setNome(nome.toLowerCase());
            setNumero(indice(nome.toLowerCase()));
        }
    }

    public Pokemon(int numero){
        setNome(pokemons[numero]);
        setNumero(numero + 1);
    }

    public void setNome(String nome) {
        if(!nome.equals("nidoranM")){
            this.nome = nome;
        }
        else{
            this.nome = "nidoran";
        }
    }

    public void setNumero(int numero){
        this.numero = String.format("%d",numero);
    }

    public String getNumero(){
        return this.numero;
    }

    public String getNome(){
        return this.nome;
    }

    public String getNomeImagem(){
        String nome_imagem = getNome();
        if(nome_imagem.contains(" ") || nome_imagem.contains("'")){
            nome_imagem = nome_imagem.replaceAll(" ","_");
            nome_imagem = nome_imagem.replaceAll("'","_");
        }
        if(getNumero().equals("38")){
            nome_imagem = "nidoran_macho";
        }
        return nome_imagem;
    }

    public boolean contem(String nome){
        for(int i=0;i<pokemons.length;i++){
            if(pokemons[i].equals(nome)){
                return true;
            }
        }
        return false;
    }

    public int indice(String nome){
        for(int i=0;i<pokemons.length;i++){
            if(pokemons[i].equals(nome)){
                return i;
            }
        }
        return -1;
    }

    public static int getLenght(){
        return pokemons.length;
    }

}
